spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/lj-06?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      connect-timeout: 10000ms
      lettuce:
        pool:
          enabled: true
oss:
  name: ${OSS_NAME:local}
  bucket-name: ${OSS_BUCKET_NAME:ljwx}
  endpoint: ${OSS_ENDPOINT:}
  access-key: ${OSS_ACCESS_KEY:}
  secret-key: ${OSS_SECRET_KEY:}
  sync-delete: true
  expiry: 3600